### ISSUE TITLE
vim syntax highlighting

### ISSUE THREAD

**Issue by drtychai** [rust-analyzer/ungrammar#26]
It's not perfect, but does the job for now 😄 - feel free to copy/paste [syntax/ungram.vim][ungrammar.vim], link it, or PR:

<p align="center">
  <img width=600px src="https://raw.githubusercontent.com/drtychai/ungrammar.vim/master/screenshot-vim.png" alt="ungram.vim">
</p>

Usage w/ Plug: `Plug drtychai/ungrammar.vim`

(Edit 24/01/2021: Above screenshot updated to reflect latest update)

[ungrammar.vim]: https://github.com/drtychai/ungrammar.vim/blob/master/syntax/ungram.vim

**Comment by Iron-E** [comment]
I [also](https://github.com/Irom-E/vim-ungrammar) wrote a plugin for this! 

I didn't think to add doc comment support, but I might after seeing your implementation. Other things are mostly the same except `vim-ungrammar` supports concealing certain delimiters.
