### ISSUE TITLE
RefExpr may need keywords made optional

### ISSUE THREAD

**Issue by cphoenix-google** [rust-analyzer/ungrammar#57]
In https://github.com/rust-analyzer/ungrammar/blob/master/rust.ungram

The rule
RefExpr =
  Attr* '&' ('raw' |'mut' | 'const') Expr

does not accept patterns like 
                            &foo

Perhaps the rule should be

RefExpr =
  Attr* '&' ('raw' |'mut' | 'const')? Expr

**Comment by Veykril** [comment]
Closing as state in our other issue
