### ISSUE TITLE
rust.ungram may not accept EnumItemDiscriminant

### ISSUE THREAD

**Issue by cphoenix-google** [rust-analyzer/ungrammar#58]
In https://github.com/rust-analyzer/ungrammar/blob/master/rust.ungram

Enum's Variant is defined as "Attr* Visibility? Name FieldList ('=' Expr)?"

FieldList is defined as "RecordFieldList | TupleFieldList"

This doesn't seem to cover the EnumItemDiscriminant option described here:
https://doc.rust-lang.org/reference/items/enumerations.html

If the FieldList in Variant had a ? on it, then it would accept a bare name, as it should - but I don't know if that would be overly permissive.

**Comment by Veykril** [comment]
The grammar file is quite outdated and unmaintained at this point, rust-analyzer nowadays has its own in the main repo https://github.com/rust-lang/rust-analyzer/blob/master/crates/syntax/rust.ungram

**Comment by cphoenix-google** [comment]
Perhaps that outdated file could be updated with a comment pointing to the
more up-to-date file?

My Google search for Rust grammar pointed to the outdated one, and there
was no indication that it wasn't the current one.

**Comment by Veykril** [comment]
I've added a note https://github.com/rust-analyzer/ungrammar/commit/73678ce217b4b78df4484d9c32eca6c7dff34496

I didn't link to the new file as it doesnt quite model the proper grammar either. There isn't really an "official" document outlining the whole grammar of the language
