### ISSUE TITLE
Support for CRLF line endings

### ISSUE THREAD

**Issue by binhtddev** [rust-analyzer/ungrammar#59]
Transfered from https://github.com/binhtran432k/ungrammar-language-features/issues/86

This issue is from on my project which support language server for ungrammar. But I think it should be ask in here instead.

**Comment by matklad** [comment]
Not supporting \r\n is an explicit design decision:

https://github.com/rust-analyzer/ungrammar/blob/53bc777c2400acea2ee576123c9232d50731563c/src/lexer.rs#L113

The proper way to fix this is on the editor/vcs site.

**Comment by elenakrittik** [comment]
> Not supporting \r\n is an explicit design decision

That's perfectly understandable, but is there a particular reason? The line you linked only confirms your words about the decision's explicitness, but doesn't get into the reasoning.

**Comment by matklad** [comment]
To reduce overall system complexity: `\n` as a sole line separator is simpler than having two different separators. These days, even notepad.exe understands `\n`, so there's no fundamental _need_ to support `\r\n`.
