### ISSUE TITLE
Unused nodes

### ISSUE THREAD

**Issue by dtolnay** [rust-analyzer/ungrammar#6]
These two nodes are currently unused by any other nodes; there might be others:

https://github.com/rust-analyzer/ungrammar/blob/07d5806c9345e43c5fb2baa427bc149c8808a10f/rust.ungram#L68-L73

Are these needed as intermediate data structures in your parser without being present in the syntax tree, or can they be removed from the ungrammar?

**Comment by matklad** [comment]
These are alternative top-level nodes for macro expansion. Ie, top-level macro expands to MacroItems nodes.

They are somewhat of an implementation detail of rust-analyzer at the moment, maybe we can/should unify them with file/block contents nodes.

In other words, we probably need to change something around here, but to figure out what exactly, we need to carefully review macro expansion needs.

**Comment by Veykril** [comment]
Closing as the grammar file is no longer maintained
